return {
    -- The inclusion of the below line tells the language server that the first parameter of the cutscene is `WorldCutscene`.
    -- This allows it to fetch us useful documentation that shows all of the available cutscene functions while writing our cutscenes!

    ---@param cutscene WorldCutscene
    kris = function(cutscene)        
        local icicles = {}
        local function pierce(x, y, ice)
            Game.world:addChild(ice)
            ice.x = x 
            ice.y = y
            ice:setScale(2)
            ice.scale_y = 0
            ice.layer = 9999
            table.insert(icicles, ice)
            Game.world.timer:tween(0.2, ice, {scale_y = -2}, "in-expo")
        end 
        local kx, ky = cutscene:getMarker("kris")
        local kris = cutscene:getCharacter("kris")
        cutscene:wait(cutscene:walkTo(kris, kx, ky, 2))
        cutscene:wait(cutscene:playSound("short_alert"))
        local spx, spy = kris:getRelativePos(kris.width/2, kris.height/2, Game.world)
        local sprite = Sprite("effects/icicle", spx, spy + 40)
        local dummy = Sprite("effects/icicle")
        local snd = Assets.playSound("rise")
        Game.world:addChild(sprite)
        sprite:setScale(2)
        sprite.scale_y = 0
        sprite.layer = 999
        Game.world.timer:tween(0.2, sprite, {scale_y = -2}, "in-expo")
        cutscene:wait(0.2)
        kris:shake()
        Assets.playSound("damage")
        kris:setSprite("fell")
        Game.world.timer:tween(0.2, sprite, {scale_y = 0}, "out-expo")
        cutscene:wait(0.2)
        cutscene:wait(cutscene:playSound("short_alert"))
        Assets.playSound("rise")
        pierce(kris.x - 70, spy + 38, Sprite("effects/icicle"))
        pierce(kris.x + 70, spy + 38, Sprite("effects/icicle"))
        local middle, _ = kris:getRelativePos(kris.width/2, kris.height, Game.world)
        pierce(middle, spy - 2, Sprite("effects/icicle"))
        pierce(middle, spy + 70, Sprite("effects/icicle"))
        Game.world.music:play("gallery")
        Game.world.music:setVolume(0)
        Game.world.music:fade(0.5, 0.2)
        local noelle = Game.world:spawnNPC("noelle", 2277, 273)
        noelle:setSprite("end")
        cutscene:wait(0.2)
        cutscene:panTo(kris.x + 200, Game.world.camera.y, 1.4, "out-cubic")
        cutscene:wait(1)
        Assets.playSound("wing")
        noelle:shake(2)
        noelle:resetSprite()
        noelle:setOrigin(0, 1)
        noelle:setSprite("walk_happy")
        noelle:setFacing("left")
        cutscene:wait(0.4)
        cutscene:setSpeaker("noelle")
        cutscene:text("* There you are,[wait:5] Kris.", "sad_side")
        cutscene:text("* Finally quiet,[wait:5] aren't you?", "down_smile")
        noelle:walkTo(noelle.x, noelle.y - 40, 0.6)
        cutscene:wait(0.6)
        noelle:resetSprite()
        noelle:setSprite("head_lowered_look_left")
        local function bumpshake(intensity)
            Assets.playSound("bump")
            kris:shake(intensity)
        end 
        cutscene:wait(0.6)
        cutscene:text("* All those innocent people you killed...", "sad")
        bumpshake(3)
        cutscene:wait(0.2)
        cutscene:text("* and my [shake:1]father[shake:0]...", "upset_down")
        bumpshake(3)
        cutscene:wait(0.2)
        cutscene:text("[noskip]* You can't leave.[wait:10]\n* You won't leave,[wait:5] will you,[wait:5] Kris?[wait:5][next]", "terrified_twitch")
        cutscene:wait(0.2)
        cutscene:setSpeaker(nil)
        cutscene:text("* Wow, what did that foreigner do to our princess...?")
        cutscene:setSpeaker("noelle")
        cutscene:text("* Kris, why...[wait:5] why would you kill my father?", "what_smile_b")
        bumpshake(3)
        cutscene:text("* [shake:1]This[shake:0] dark world.[wait:5] I made for him to stay alive,[wait:5] have our last moments.", "dejected")
        noelle:resetSprite()
        noelle:setSprite("walk_happy")
        noelle:walkTo(noelle.x - 75, noelle.y, 1.4)
        cutscene:wait(1.4)
        cutscene:text("[shake:2][noskip][speed:0.7]* And you ruined it all,[wait:5] Kris![wait:5][next]", "terrified_side")
        Game.world.music:fade(0, 1)
        cutscene:wait(1)
        kris:setAnimation("swing")
        Assets.playSound("scytheburst")
        for _, ice in ipairs(icicles) do 
            ice:shake(2)
            ice:flash(0, 0, 100, COLORS.red)
            Assets.playSound("hurt")
            Game.world.timer:tween(0.4, ice, {scale_y = 0}, "out-expo")
        end 
        cutscene:wait(0.4)
        noelle:setSprite("shocked")
        kris:resetSprite()
        kris:setFacing("right")
        cutscene:wait(cutscene:playSound("wing"))
        noelle:resetSprite()
        noelle:setSprite("walk_happy")
        noelle:setFacing("right")
        cutscene:wait(cutscene:playSound("wing"))
        noelle:walkTo(noelle.x + 20, noelle.y, 0.7, "left")
        cutscene:wait(0.7)
        cutscene:text("* So persistent,[wait:5] you never give up,[wait:5] do you,[wait:5] Kris?", "upset_down_b")
        kris:walkTo(kris.x + 300, kris.y, 4)
        cutscene:wait(0.3)
        noelle:setOrigin(0.5, 1)
        noelle.scale_x = -2
        Assets.playSound("short_alert", 0.7)
        noelle:setAnimation("spell", function()
            local rx, ry = kris:getRelativePos(kris.width, kris.height, Game.world)
            rx = rx + 10
            local sprite = Sprite("effects/ice_shard")
            sprite.x = noelle.x - 41
            sprite.y = noelle.y - 74
            sprite:setOrigin(0.5, 0.5)
            sprite.layer = 9999 
            sprite:setScale(1.5)
            Game.world:addChild(sprite)
            sprite.rotation = MathUtils.angle(sprite.x, sprite.y, rx, ry)
            Assets.playSound("bigcut")  
            sprite:slideTo(rx, ry, 0.3, "linear", function()
                Game.world.music:fade(0.2, 0.3)
                Assets.playSound("wing")
                noelle:resetSprite()
                noelle.scale_x = 2
                noelle:setSprite("walk_happy")
                noelle:setFacing("left")
                sprite:fadeOutAndRemove(0.3)
                kris:resetPhysics()
                kris:walkTo(kris.x - 30, kris.y, 0.4, "right", true)
            end)
        end)
        cutscene:wait(0.5)
        Game.world.music:fade(0, 0.5)
        cutscene:wait(0.5)
        cutscene:text("* Trying to leave,[wait:5] huh,[wait:5] Kris?", "upset_down_b")
        cutscene:text("* You can't run away from your problems.", "upset_down")
        cutscene:text("* I'm not going to let you.", "upset")
        cutscene:startEncounter("noelle", nil, {{"noelle", noelle}})
    end 
}
