return {
    -- The inclusion of the below line tells the language server that the first parameter of the cutscene is `WorldCutscene`.
    -- This allows it to fetch us useful documentation that shows all of the available cutscene functions while writing our cutscenes!

    ---@param cutscene WorldCutscene
    shadow = function(cutscene)
        cutscene:loadMap("room4") -- placeholder code 
        local kris = cutscene:getCharacter("kris")
        kris:setPosition(536, 280) 
        cutscene:wait(0.3)-- also change code 
        Assets.playSound("damage")
        kris:shake()
        local fx = kris:addFX(ColorMaskFX(COLORS.red, 1))
        kris:setSprite("sit")
        kris.layer = 0.459
        Game.world.timer:tween(0.3, fx, {amount = 0})
        cutscene:wait(0.7)
        cutscene:panTo(Game.world.camera.x + 200, Game.world.camera.y, 2, "out-sine")
        cutscene:wait(1)
        local noelle = cutscene:spawnNPC("noelle", 926, 286)
        local k = cutscene:spawnNPC("kris", 859, 286)
        k:setFacing("left")
        noelle.alpha = 0 
        local kfx = k:addFX(ColorMaskFX(COLORS.black, 1))
        local nfx = noelle:addFX(ColorMaskFX(COLORS.black, 1))
        k.alpha = 0
        noelle:setSprite("walk_sad")
        noelle:setFacing("left")
        Game.world.music:play("wind")
        Game.world.timer:tween(1, noelle, {alpha = 1})
        Game.world.timer:tween(1, k, {alpha = 1})
        Game.world.timer:tween(1, kris, {alpha = 0})
        local effect = OverworldSnowEffect()
        Game.world:addChild(effect)
        effect.layer = noelle.layer - 0.01 
        cutscene:wait(1)
        k:walkTo(559, k.y, 6)
        noelle:walkTo(623, noelle.y, 6)
        cutscene:wait(0.5)
        cutscene:text("*[noskip] Kris..[wait:2] where are we going...?[wait:5][next]", "afraid", "noelle") 
        cutscene:wait(1)
        kris.alpha = 1
        kris.layer = effect.layer - 0.001
        cutscene:text("*[noskip] To...[wait:2] get stronger?[wait:5][next]", "sad_side", "noelle")
        cutscene:wait(0.5)
        effect:remove()
        Game.world.music:pause()
        noelle:fadeOutAndRemove(1)
        k:fadeOutAndRemove(1)
        cutscene:wait(0.3)
        cutscene:wait(1)
        cutscene:setSpeaker("shadow")
        cutscene:text("* Don't you remember all this?")
        Assets.playSound("bump")
        kris:shake()
        cutscene:wait(0.5)
        cutscene:text("* Over here,[wait:5] Kris.")
        local shadow = Game.world:spawnNPC("shadow", 546, 262)  
        shadow:setAnimation("ball")
        shadow:setScale(1)
        kris:shake()
        Assets.playSound("grab")
        Assets.playSound("jump")
        local start_x = shadow.x
        local start_y = shadow.y
        local target_x = 863
        local target_y = 300
        local arc_height = 80  
        local duration = 0.8 
        local elapsed_time = 0
Game.world.timer:during(duration, function()
    elapsed_time = elapsed_time + DT
    local progress = math.min(1.0, elapsed_time / duration)
    shadow.x = Utils.lerp(start_x, target_x, progress)
    local base_y = Utils.lerp(start_y, target_y, progress)
    local height_offset = 4 * arc_height * progress * (1 - progress)
    
    shadow.y = base_y - height_offset
end, function()
    shadow:setSprite("landed")
    shadow:addFX(ColorMaskFX(COLORS.black))
    shadow:addFX(OutlineFX())
    shadow.sprite.scale_y = 0
    shadow.sprite.scale_x = 2
end)
cutscene:wait(duration)
local snd = Assets.playSound("appear")
Game.world.timer:tween(snd:getDuration(), shadow.sprite, {scale_y = -1}) 
Game.world.timer:during(snd:getDuration(), function()
shadow:setPosition(893, 323)
end)
Game.world.music:play("gallery")
Game.world.music:setVolume(0)
Game.world.music:fade(0.7, 1)
cutscene:wait(1.3)
Assets.playSound("wing")
shadow:shake()
shadow.sprite.scale_y = 2
shadow.y = 248
shadow:setSprite("left")
local function bumpshake()
kris:shake()
Assets.playSound("bump")
Game.stage:shake()
end 
cutscene:wait(0.5)
cutscene:text("* Heh.[wait:5] Look at you.[wait:5] So helpless.")
bumpshake()
cutscene:wait(0.5)
cutscene:text("* That [color:red][shake:1]SOUL[color:reset][shake:0] of yours...")
bumpshake()
cutscene:wait(0.5)
cutscene:text("* Controlling you like a puppet...")
bumpshake()
cutscene:wait(0.5)
cutscene:text("*[noskip] Your actions don't matter,[wait:5] do they?[wait:8][next]")
bumpshake()
cutscene:wait(0.5)
cutscene:text("* Berdly, Spamton, [shake:1]Noel[shake:0]-[next]")
local fx = kris:addFX(ColorMaskFX(COLORS.red, 1))
Assets.playSound("weaponpull_fast")
kris:setAnimation("battle/attack_ready")
shadow.y = 246
Game.world.timer:tween(0.5, fx, {amount = 0})
cutscene:wait(1.8)
cutscene:text("* You're so desperate to break free,[wait:5] huh?")
cutscene:text("* Kris...[wait:5]")
Game.world.music:fade(0, 1)
cutscene:text("*[noskip][speed:0.5] You can't get rid of them.")
Game.world.music:play("shadow", 0) 
Game.world.music:fade(0.5, 1)
local storm_overlay = ThunderTint()
Game.stage:addChild(storm_overlay)
storm_overlay.alpha = 0 
Game.world.timer:tween(0.5, storm_overlay, {alpha = 1})
cutscene:wait(0.5)
cutscene:text("* Heh.[wait:5]\n* But you can try getting rid\nof me.")
cutscene:startEncounter("shadow", nil, {{"shadow", shadow}}, {
    on_start = function()
        Game.stage:setWeather("thunder")
        storm_overlay:remove()
        shadow:remove()
    end
})
Game.stage:resetWeather()
Game.world.music:stop()
if Game:getFlag("shadow_v") then 
    kris:setSprite("fell")
    cutscene:wait(0.5)
    local function bumpshake()
    kris:shake(2)
    Assets.playSound("wing")
    end 
    bumpshake()
    cutscene:wait(0.2)
    bumpshake()
    cutscene:wait(0.2)
    kris:resetSprite()
    kris:setFacing("right")
    cutscene:attachCamera(1)
else 
cutscene:attachCamera(1)
kris:resetSprite()
kris:setFacing("left")
end 
    end,  
    
    ralsei = function(cutscene)
        -- getting markers is a pain 
        Game.world.music:fade(0, 5)
        local rx, ry = cutscene:getMarker("kris")
        local kris = cutscene:getCharacter("kris")
        cutscene:wait(cutscene:walkTo(kris, rx, ry, 5))
        cutscene:panTo(Game.world.camera.x + 200, Game.world.camera.y, 1, "in-quad")
        cutscene:wait(1)
        local ralsei = Game.world:spawnNPC("ralsei", 2500, kris.y + 6)
        ralsei:setFacing("left")
        ralsei:walkTo(2200, ralsei.y, 0.6)
        cutscene:wait(0.7)
        cutscene:look(ralsei, "right")
        cutscene:wait(0.2)
        cutscene:look(ralsei, "left") -- what is the difference between this and setFacing ? 
        ralsei:alert(0.5)
        cutscene:wait(0.5)
        cutscene:setSpeaker("ralsei")
        cutscene:text("* Oh,[wait:2] Kris,[wait:2] there you are!", "blush_surprise")
        cutscene:text("* Wait...[wait:10] where's Susie?", "surprise_confused")
        cutscene:wait(0.3)
        cutscene:text("* W-[wait:2]well, I'm just glad I found you,[wait:5] Kris!", "blush_smile")
        cutscene:wait(0.3)
        ralsei:setSprite("walk/left")
        ralsei.sprite:play(0.1, true)
        cutscene:text("[noskip]* This dark world is so empty...[next]", "small_smile_side")
        ralsei:resetSprite()
        ralsei:setFacing("left")
        ralsei:walkTo(ralsei.x - 200, ralsei.y, 3)
        cutscene:text("[speed:1.2][noskip]* Anyways,[wait:2] I believe if we continue to the right.[next]", "small_smile")
        cutscene:text("[speed:1.2][noskip]* We should be at the fountain in no time! and-[next]", "small_smile")
        ralsei:resetPhysics()
        Assets.playSound("break1")
        local fx = kris:addFX(ColorMaskFX(COLORS.red, 1))
        Game.world.timer:tween(0.2, fx, {amount = 0})
        kris:setAnimation("battle/attack_ready") -- apparently ANY use of functions callback ended the cutscene here???
        cutscene:wait(0.2)
        ralsei.sprite:stop()
        ralsei.sprite:resetSprite()
        ralsei.sprite:setSprite("what")
        cutscene:wait(0.3)
        cutscene:text("* K-[wait:2]Kris?!", "shock")
        cutscene:startEncounter("ralsei", nil, {{"ralsei", ralsei}})
        if not Game:getFlag("encounter#ralsei:violenced") then 
        kris:resetSprite()
        ralsei.x = ralsei.x + 200
        ralsei:resetSprite()
        cutscene:setSpeaker("ralsei")
        cutscene:wait(0.5)
        cutscene:text("* Y-[wait:2]you spared me,[wait:5] Kris?", "pleading_closed")
        ralsei:setSprite("smile")
        cutscene:text("* I[wait:2]-I knew you would!", "pleased")
        cutscene:text("* Now,[wait:2] let's go seal the fountain!", "blush_pleased")
        Game:addPartyMember("ralsei")
        local follower = Game.world:spawnFollower("ralsei",  {x = ralsei.x, y = ralsei.y, party = "ralsei"})
        ralsei:remove()
        follower:setFacing("left")
        cutscene:interpolateFollowers() 
        cutscene:attachFollowers()
        cutscene:attachCamera(1)
        cutscene:wait(1)
        end 
    end, 

    soul = function(cutscene)
        Game.fader.alpha = 1
        cutscene:detachCamera()
        Game.world.fader.alpha = 1
        local kris = cutscene:getCharacter("kris")
        Game.world:addFX(ShaderFX("desat", {amount = 1.5}), "desat")
        Game.world:addFX(ShaderFX("desat", {amount = 1}), "desat2")
        Game.world.music:play("wind_normal")
        cutscene:wait(2)  
        local function resetFader(full)
            Game.fader.alpha = full
            Game.world.fader.alpha = full 
        end 
        local snd = Assets.playSound("static", 0.4, 1.2)
        kris:setSprite("soul/dead_2")
        Game.world.timer:tween(snd:getDuration(), Game.world.fader, {alpha = 0})
        Game.world.timer:tween(snd:getDuration(), Game.fader, {alpha = 0})
        cutscene:wait(0.6)
        resetFader(1)
        Assets.playSound("step1")
        kris:setPosition(200, 355)
        Assets.playSound("step2")
        cutscene:wait(0.5)
        -- resetFader(0)
        kris:setAnimation({"soul/take", 0.2, false})
        cutscene:wait(0.2)
        resetFader(0)
        cutscene:wait(0.1)
        local snd = Assets.playSound("static", 0.4, 1.2)
        cutscene:wait(snd:getDuration())
        resetFader(1)
        cutscene:wait(0.5)
        for i = 1, 5 do 
            Assets.playSound("hurt")
            cutscene:wait(0.1)
        end
        cutscene:wait(cutscene:playSound("break2")) 
        cutscene:wait(0.3)
        Assets.playSound("impact")
        resetFader(0)
        local rect = Rectangle(0, 0, 9999, 9999)
        rect:setParallax(0, 0)
        rect:setColor(COLORS.black)
        rect.layer = WORLD_LAYERS["below_textbox"]
        Game.world:addChild(rect)
        cutscene:wait(0.2)
        Game.world:removeFX("desat")
        Game.world:removeFX("desat2")
        cutscene:wait(0.5)
        cutscene:text("* Suddenly,[wait:2] the world goes dark around [shake:1]you[shake:0].")
        cutscene:choicer({"Proceed", "Proceed"}, {color = COLORS.red, highlight = COLORS.red})
        Game.world.music:stop()
        cutscene:wait(cutscene:playSound("noelle"))
        -- Game:addPartyMember("noelle")
        -- Game:removePartyMember("kris")
        cutscene:attachCamera()
        kris:resetSprite()
        kris:setPosition(110, 342)
        rect:fadeOutAndRemove(0.5)
        cutscene:wait(0.5)
        -- cutscene:wait(cutscene:mapTransition("recep6"))
        -- Game.world.music:play("wind_normal")
        -- cutscene:detachCamera()
        -- Game.world.camera:setPosition(997, 240)
        -- local noelle = cutscene:getCharacter("noelle")
        -- noelle:setPosition(2877, 622)
        -- noelle:setAnimation("float")
        -- rect:fadeOutAndRemove(0.5)
        -- cutscene:wait(0.5)
    end 
}
