return {
    -- The inclusion of the below line tells the language server that the first parameter of the cutscene is `WorldCutscene`.
    -- This allows it to fetch us useful documentation that shows all of the available cutscene functions while writing our cutscenes!

    ---@param cutscene WorldCutscene
    fall = function(cutscene)
            Game:removePartyMember("noelle")
            cutscene:wait(2)
            cutscene:setTextboxTop(true)
            cutscene:wait(cutscene:mapTransition("Noellehallway"))
            Game.world.music:play("wind", 0.3)
            local noelle = cutscene:spawnNPC("noelle", 225, -100)
            Game.world:setCameraTarget(noelle)
            local kris = cutscene:getCharacter("kris")
            kris.sprite.visible = false 
            cutscene:wait(1)
            noelle:setAnimation("fall")
            noelle:slideTo(239, 266, 1, "in-cubic")
            cutscene:wait(1)
            Assets.playSound("dtrans_flip")
            noelle.sprite.scale_x = -1
            noelle.x = noelle.x + 50 
			noelle:slideTo(300, 266, 0.5, "out-cubic")
            noelle:setSprite("collapsed")
            cutscene:wait(2)
            for i = 1, 3 do 
                noelle:shake(2)
                cutscene:wait(cutscene:playSound("wing"))
                cutscene:wait(0.3)
            end 
            noelle:resetSprite()
            noelle.sprite.scale_x = 1
            noelle.x = noelle.x - 50 
            noelle:setFacing("up")
            cutscene:wait(0.4)
            cutscene:setSpeaker("noelle")
            cutscene:text("* (What is this place...?)")
            noelle:setSprite("head_lowered_look_left")
            cutscene:wait(0.2)
			noelle:shake(1)
            cutscene:text("* (It's so cold...)")
            noelle:setSprite("headtilt")
            cutscene:wait(0.4)
			cutscene:text("* (The sky...[wait:2] it's so dark, and creepy)")
            cutscene:wait(0.4)
			noelle:setFacing("up")
			cutscene:text("* (where are the stars?, or even the moon?)")
            cutscene:wait(2)
            cutscene:setTextboxTop(false)
            cutscene:text("* O-oh right!", "shock")
            Assets.playSound("wing")
            noelle:resetSprite()
            noelle:shake(2)
            noelle:setSprite("walk_sad/right_1")
            cutscene:wait(0.8)
            cutscene:text("* I-[wait:2]I can't forget about dad!", "afraid_b")
            noelle:setSprite("walk_look_up")
            noelle:setFacing("right")
            cutscene:text("* I have to go find him!", "afraid")
            noelle:walkTo(855, noelle.y, 12)
            cutscene:wait(2)
            cutscene:text("[noskip]* So,[wait:2] this is what Susie and Queen were talking about...[wait:7]", "confused_surprise_b", "noelle", {auto = true})
            cutscene:wait(3)
            cutscene:text("[noskip]* What a \"dream\"[wait:2] that was![wait:9]", "blush_smile", "noelle", {auto = true}) 
			cutscene:text("fahaha[wait:3]", "blush_finger", "noelle", {auto = true})
            cutscene:wait(3)
            cutscene:text("[noskip]* Wait...[wait:7]", "surprise_frown_b", "noelle", {auto = true})
            cutscene:text("[noskip]* Does that mean [shake:1]Berdly[shake:0] really did-[wait:2]", "surprise_frown_b", "noelle", {auto = true})
            noelle:resetPhysics()
            local fx = noelle:addFX(ColorMaskFX(COLORS.red, 1))
            noelle:shake(2)
            Assets.playSound("damage")
            noelle:setSprite("kneel_right")
            Game.world.timer:tween(0.3, fx, {amount = 0})
            cutscene:wait(1.5)
            cutscene:text("* W-[wait:2]what just happened?", "surprise_frown_b")
            cutscene:text("* My hand![wait:5]\n* it's bleeding!", "surprise_smile")
            cutscene:wait(0.2)
            Assets.playSound("break1")
            noelle.sprite:flash()
            cutscene:wait(1.2)
            Assets.playSound("wing")
            noelle:shake(2)
            noelle:resetSprite()
            noelle:setAnimation("pray")
            cutscene:wait(0.5)
            cutscene:text("* [noskip][speed:0.7][shake:1]...", "down_smile")
            cutscene:wait(1.2)
            cutscene:text("*[noskip][speed:0.7] Kris...faha[wait:5] Kris, I can still remember their voice", "down_smile")
			cutscene:text("*[noskip][speed:0.7] telling me to get stronger", "down_smile")
            cutscene:text("* [noskip][speed:0.7]This thorn...[wait:5] it helps me... be strong", "sad_side")
            cutscene:text("* [noskip][speed:0.7]I need to find more [shake:1]enemies[shake:0].", "upset_down_b")
            Assets.playSound("wing")
            noelle:shake(2)
            noelle:resetSprite()
            noelle:setSprite("walk_sad")
            noelle:setFacing("right")
            cutscene:wait(0.4)
            noelle:walkTo(1200, noelle.y, 6)
            cutscene:wait(cutscene:fadeOut(2))
            cutscene:wait(cutscene:mapTransition("room1"))
            cutscene:fadeIn(0.1)
    end
}
