return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 6,
  nextobjectid = 29,
  properties = {
    ["border"] = "leaves",
    ["inside"] = true,
    ["light"] = true,
    ["music"] = "hometown"
  },
  tilesets = {
    {
      name = "hometownobjects",
      firstgid = 1,
      filename = "../../../../../tilesets/hometownobjects.tsx",
      exportfilename = "../../../../../tilesets/hometownobjects.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../../../assets/sprites/world/maps/hometown/interior/police.png",
      id = 2,
      name = "room",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          class = "",
          shape = "rectangle",
          x = 356,
          y = 112,
          width = 164,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          class = "",
          shape = "rectangle",
          x = 520,
          y = 28,
          width = 40,
          height = 372,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          class = "",
          shape = "rectangle",
          x = 120,
          y = 28,
          width = 400,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          class = "",
          shape = "rectangle",
          x = 360,
          y = 400,
          width = 200,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          class = "",
          shape = "rectangle",
          x = 360,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 400,
          width = 200,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 28,
          width = 40,
          height = 372,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          class = "",
          shape = "rectangle",
          x = 240,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          class = "",
          shape = "rectangle",
          x = 120,
          y = 246,
          width = 94,
          height = 104,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          class = "",
          shape = "rectangle",
          x = 120,
          y = 152,
          width = 94,
          height = 74,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          class = "",
          shape = "rectangle",
          x = 120,
          y = 152,
          width = 238,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          class = "",
          shape = "rectangle",
          x = 360,
          y = 360,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          class = "",
          shape = "rectangle",
          x = 460,
          y = 264,
          width = 60,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          class = "",
          shape = "rectangle",
          x = 258,
          y = 256,
          width = 138,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          class = "",
          shape = "rectangle",
          x = 358,
          y = 192,
          width = 162,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 15,
          name = "",
          class = "",
          shape = "rectangle",
          x = 354,
          y = 206,
          width = 166,
          height = 138,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          class = "",
          shape = "rectangle",
          x = 242,
          y = 330,
          width = 170,
          height = 118,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          class = "",
          shape = "rectangle",
          x = 150,
          y = 168,
          width = 56,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = 280,
          y = 480,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "up",
            ["map"] = "light/hometown/town_south",
            ["marker"] = "entrypolice"
          }
        },
        {
          id = 9,
          name = "interactable",
          class = "",
          shape = "rectangle",
          x = 120,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "{hometown.text.well_cared_for_flowers_b7a2ab3eb8}"
          }
        },
        {
          id = 26,
          name = "npc",
          class = "",
          shape = "point",
          x = 201,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "napstablook",
            ["cutscene"] = "hometown.blook"
          }
        },
        {
          id = 27,
          name = "interactable",
          class = "",
          shape = "rectangle",
          x = 239,
          y = 89,
          width = 85,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "{hometown.text.you_skimmed_a_news_article_about_undyne_7314aded4d}",
            ["text2"] = "{hometown.text.new_police_chief_undyne_s_explosive_debut_4a0dbe4e76}",
            ["text3"] = "{hometown.text.passionate_young_rookie_becomes_the_new_police_c_94fec8a5c7}",
            ["text4"] = "{hometown.text.though_energetic_it_may_be_hard_to_live_up_to_th_4e9d0f0353}",
            ["text5"] = "{hometown.text.after_asgore_dreemurr_was_removed_from_the_force_2e3e1db0ae}",
            ["text6"] = "{hometown.text.there_s_no_need_to_read_any_more_ee542f6062}"
          }
        },
        {
          id = 28,
          name = "interactable",
          class = "",
          shape = "rectangle",
          x = 123,
          y = 267,
          width = 80,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "{hometown.text.photos_of_chief_undyne_and_deputy_napstablook_c7d1e0961a}",
            ["text2"] = "{hometown.text.undyne_is_rescuing_all_of_catti_s_family_from_a__cced8ca4c8}",
            ["text3"] = "{hometown.text.napstablook_is_also_stuck_in_the_tree_somehow_a8c84081cc}"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 25,
          name = "spawn",
          class = "",
          shape = "point",
          x = 320,
          y = 440,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
